# Which is equivalent to
format = """
$username\
$hostname\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$fill\
$cmd_duration\
$cmake\
$cobol\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$time\
$line_break\
$jobs\
$battery\
$status\
$shell\
$character"""

[aws]
format = '[$symbol($profile)(\($region\))(\[$duration\])]($style) '
disabled = true

[cmake]
format = '[$symbol($version)]($style) '

[cmd_duration]
format = '[$duration ]($style) '
style = 'white dimmed'

[cobol]
format = '[$symbol($version)]($style) '

[conda]
format = '[$symbol$environment]($style) '

[crystal]
format = '[$symbol($version)]($style) '

[dart]
format = '[$symbol($version)]($style) '

[deno]
format = '[$symbol($version)]($style) '

[docker_context]
format = '[$symbol$context]($style) '

[dotnet]
format = '[$symbol($version)(🎯 $tfm)]($style) '

[elixir]
format = '[$symbol($version \(OTP $otp_version\))]($style) '

[elm]
format = '[$symbol($version)]($style) '

[erlang]
format = '[$symbol($version)]($style) '

[fill]
symbol = " "

[gcloud]
format = '[$symbol$account(@$domain)(\($region\))]($style) '

[git_branch]
style = 'bold green'
format = '[\($branch]($style)'

[git_status]
style = 'bold green'
format = "[( *$conflicted$untracked$modified$renamed$deleted)( $ahead_behind$stashed)\\) ]($style)"
stashed = "≡"

[git_state]
style = 'bold green'
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[golang]
format = '[$symbol($version)]($style) '

[helm]
format = '[$symbol($version)]($style) '

[hg_branch]
format = '[$symbol$branch]($style) '

[java]
format = '[$symbol($version)]($style) '

[julia]
format = '[$symbol($version)]($style) '

[kotlin]
format = '[$symbol($version)]($style) '

[kubernetes]
format = '[$symbol$context( \($namespace\))]($style) '

[lua]
format = '[$symbol($version)]($style) '

[memory_usage]
format = '$symbol[$ram( | $swap)]($style) '

[nim]
format = '[$symbol($version)]($style) '

[nix_shell]
format = '[$symbol$state( \($name\))]($style) '

[nodejs]
format = '[($version)]($style) '
style = 'green dimmed'
symbol = ''

[ocaml]
format = '[$symbol($version)(\($switch_indicator$switch_name\))]($style) '

[openstack]
format = '[$symbol$cloud(\($project\))]($style) '

[package]
format = '[$version]($style) '
style = 'dimmed 208'

[perl]
format = '[$symbol($version)]($style) '

[php]
format = '[$symbol($version)]($style) '

[pulumi]
format = '[$symbol$stack]($style) '

[purescript]
format = '[$symbol($version)]($style) '

[python]
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '

[red]
format = '[$symbol($version)]($style) '

[ruby]
format = '[$symbol($version)]($style) '

[rust]
format = '[$symbol($version)]($style) '

[scala]
format = '[$symbol($version)]($style) '

[sudo]
format = '[as $symbol] '

[swift]
format = '[$symbol($version)]($style) '

[terraform]
format = '[$symbol$workspace]($style) '

[time]
format = '[$time]($style) '
disabled = false
style = "white dimmed bold"

[username]
format = '[$user]($style)\]'

[vagrant]
format = '[$symbol($version)]($style)\]'

[vlang]
format = '[$symbol($version)]($style)\]'

[zig]
format = '[$symbol($version)]($style) '
